apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: Trace
          matcherRegex: 'trace_id="([a-f0-9]{32})"'
          url: '$${__value.raw}'
          datasourceUid: tempo
        - name: Correlation
          matcherRegex: 'correlation_id="([a-f0-9-]+)"'
          url: '/explore?orgId=1&left={"queries":[{"expr":"{correlation_id=\\\"$${__value.raw}\\\"}"}]}'
          datasourceUid: loki
